### ISSUE TITLE
Inconsistency of Spaces in Documentation Source

### ISSUE THREAD

**Issue by mamat-rahmat** [Bauble/bauble.classic-docs.i18n#2]
I found that in documentation source, some files are use double spaces after period, while the other use one. This causing confusion to translator (I found that some translator eventually use one space instead of double space).

For example those are using double spaces after period : 
- https://raw.githubusercontent.com/Bauble/bauble.classic-docs.i18n/master/source/installing.rst
- https://raw.githubusercontent.com/Bauble/bauble.classic-docs.i18n/master/source/editing.rst

While majority is using one space after period, for example : 
- https://raw.githubusercontent.com/Bauble/bauble.classic-docs.i18n/master/source/administration.rst
- https://raw.githubusercontent.com/Bauble/bauble.classic-docs.i18n/master/source/searching.rst

What do you think?
Oh, and if it is needed, i'm happy to help uniform the space.

**Comment by mfrasca** [comment]
Hi. thanks for reviewing! since the result will be html, there's no need to keep the double space. it's probably something I do automatically, from the times I was using latex to produce documentation. I would be very glad if you would care uniform the spacing!

**Comment by mfrasca** [comment]
thank you.
